# server
spring:
  application:
    name: jenie-spring-helloworld-rest
server:
  port: 30000
  tomcat:
    basedir: .
    accesslog:
      enabled: ${helloworld.enable-access-log}
      pattern: "%{yyyy-MM-dd'T'HH:mm:ssXXX}t %a %r %s %{grpc-status}o %b %D %{x-b3-traceid}i %{x-b3-spanid}i %{Referer}i %{User-Agent}i"
management:
  endpoints:
    web:
      base-path: /monitor
  server:
    port: 8090
mongodb:
  setting:
    enabled: true
    app-name: jenie-spring-helloworld-rest
logging:
  config: classpath:logback-spring.xml
