jasypt.encryptor.password=fr2sh&rich
mongodb.setting.cluster.dev.hosts[0]=ENC(maTPz9OuaT+YwqAiiwlV0Ig4EVfvetrDw4ZRST8XTFDOaHHUtQuo9pX80wufFDHSWKoZwyBlw2QSUZgToumDUg==)
mongodb.setting.cluster.dev.hosts[1]=ENC(9DLk3b9eKRK7879DftPL9yNn39cA9yTCXT/f/v8c92HMuq0RK0LRzVKWSzjWm7U1cRxc5d6N4GOP5jJWy+wOEQ==)
mongodb.setting.cluster.dev.hosts[2]=ENC(EG9k4b9QQ0yc/Mt1/zWT5pYsOBfIEk0tVIBMKTngVZZNeRnD+9YfYY6JjwbiQCwOEk+nrpN56aeZiD7/HXoa9w==)
mongodb.setting.cluster.dev.user=ENC(8REbgXGAWryxCMdlr9gXcC1WsHtpEnHAweJU+bTwm+ljmR8o0Zd+ih/rNKSQI8Ha)
mongodb.setting.cluster.dev.password=ENC(XY9T43OG9qXTLiVqqLWay6YYocxvmxGTsraR0ifNQf+8dxsyCo3bvbHaMHe0Wtnc)
mongodb.setting.cluster.dev.min-size=2
