# server
spring.application.name=jenie-spring-helloworld
server.port=30000

# log
server.tomcat.basedir=.
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd
server.tomcat.accesslog.pattern=%{yyyy-MM-dd HH:mm:ss}t %s %r %b %h %{User-Agent}i
management.endpoints.web.base-path=/monitor
management.server.port=8090

# mongodb
mongodb.setting.enabled=true
mongodb.setting.app-name=jenie-spring-helloworld

# logging
logging.config=classpath:logback-spring.xml