# server
spring.application.name=jenie-spring-helloworld-grpc
grpc.server.port=30006

# mongodb
mongodb.setting.enabled=true
mongodb.setting.app-name=jenie-spring-helloworld-grpc

# logging
logging.config=classpath:logback-spring.xml