spring.application.name=jenie-spring-helloworld-armeria-grpc-reactive
spring.main.web-application-type=none
server.port=30009
armeria.ports[0].port=30009
armeria.enable-metrics=false
mongodb.setting.enabled=true
mongodb.setting.app-name=jenie-spring-helloworld-armeria-grpc-reactive
