mongodb:
  setting:
    cluster:
      dev:
        hosts:
          - ${MONGO_HOST_0}
          - ${MONGO_HOST_1}
          - ${MONGO_HOST_2}
        user: ${MONGO_USER}
        password: ${MONGO_PASS}
        min-size: ${MONGO_POOL_MIN}
        max-size: ${MONGO_POOL_MAX}
        max-connecting: ${MONGO_MAX_CONN}
    router-type: ${MONGO_ROUTER_TYPE}

helloworld:
  server-compression: ${COMPRESSION}
  use-blocking-task-executor: ${BLOCKING_EXECUTOR}
  crypto:
    password: ${CRYPTO_PASS}
    salt: ${CRYPTO_SALT}