# server
spring.application.name=jenie-spring-helloworld-armeria-grpc-reactive
server.port=30009

armeria.ports[0].port=30009
armeria.enable-metrics=false

# mongodb
mongodb.setting.enabled=true
mongodb.setting.app-name=jenie-spring-helloworld-armeria-grpc-reactive
