spring:
  application:
    name: jenie-spring-helloworld-rest-reactive
server:
  port: 30007
management:
  endpoints:
    web:
      base-path: /monitor
  server:
    port: 8090
mongodb:
  setting:
    enabled: true
    app-name: jenie-spring-helloworld-rest-reactive
logging:
  config: classpath:logback-spring.xml