# server
spring.application.name=jenie-spring-helloworld-rest-reactive
server.port=30006

# log
server.tomcat.basedir=.
server.tomcat.accesslog.enabled=false
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd
server.tomcat.accesslog.pattern=%{yyyy-MM-dd HH:mm:ss}t %s %r %b %h %{User-Agent}i

management.endpoints.web.base-path=/monitor
management.server.port=8090

# mongodb
mongodb.setting.enabled=true
mongodb.setting.app-name=jenie-spring-helloworld-rest-reactive

# logging
logging.config=classpath:logback-spring.xml