# server
spring.application.name=jenie-spring-helloworld-rest-reactive
server.port=30007
server.netty.idle-timeout=3s
server.netty.validate-headers=false

# log
management.endpoints.web.base-path=/monitor
management.server.port=8090

# mongodb
mongodb.setting.enabled=true
mongodb.setting.app-name=jenie-spring-helloworld-rest-reactive

# logging
logging.config=classpath:logback-spring.xml