# server
spring.application.name=jenie-spring-helloworld-armeria-grpc
spring.main.web-application-type=none

armeria.ports[0].port=30005
armeria.access-log.type=disabled
armeria.enable-metrics=false

armeria.worker-group=4
armeria.max-num-connections=2000
armeria.http2-initial-connection-window-size=1024KB
armeria.http2-initial-stream-window-size=256KB
armeria.http2-max-streams-per-connection=1000
armeria.idle-timeout=30s

armeria.internal-services.port=8090
management.endpoints.web.exposure.include=info
management.endpoint.info.enabled=true

# mongodb
mongodb.setting.enabled=true
mongodb.setting.app-name=jenie-spring-helloworld

# logging
logging.config=classpath:logback-spring.xml