# server
spring.application.name=jenie-spring-helloworld-armeria-grpc
spring.main.web-application-type=none

armeria.ports[0].port=30005
armeria.access-log.type=disabled
armeria.enable-metrics=false
armeria.internal-services.port=8090
management.endpoints.web.exposure.include=info
management.endpoints.web.base-path=/monitor
management.endpoint.info.enabled=true

# mongodb
mongodb.setting.enabled=true
mongodb.setting.app-name=jenie-spring-helloworld

# logging
logging.config=classpath:logback-spring.xml