# server
spring.application.name=jenie-spring-helloworld-armeria-grpc
spring.main.web-application-type=none

armeria.ports[0].port=30005
armeria.access-log.type=disabled
armeria.enable-metrics=false

# mongodb
mongodb.setting.enabled=true
mongodb.setting.app-name=jenie-spring-helloworld-armeria-grpc

# logging
logging.config=classpath:logback-spring.xml