jasypt.encryptor.password=${JASYPT_PASS}
armeria.access-log.type=${ACCESS_LOG_TYPE}
mongodb.setting.cluster.dev.hosts[0]=${MONGO_HOST_0}
mongodb.setting.cluster.dev.hosts[1]=${MONGO_HOST_1}
mongodb.setting.cluster.dev.hosts[2]=${MONGO_HOST_2}
mongodb.setting.cluster.dev.user=${MONGO_USER}
mongodb.setting.cluster.dev.password=${MONGO_PASS}
mongodb.setting.cluster.dev.min-size=2
mongodb.setting.router-type=${MONGO_ROUTER_TYPE}
helloworld.server-compression=${COMPRESSION}
helloworld.use-blocking-task-executor=${BLOCKING_EXECUTOR}
helloworld.use-grpc-json-transcoder=${GRPC_JSON_TRANSCODER}
