jasypt.encryptor.password=jenie
mongodb.setting.cluster.local.hosts[0]=ENC(NGKKCGpGvxEe+qe/9Kn/uFd31ZQt6/TLywu7K0x38V3ymF7gOTZNQrsM1LG0LdZJ)
mongodb.setting.cluster.local.min-size=2
mongodb.setting.router-type=simple