mongodb.setting.cluster.local.hosts[0]=ENC(3ecd3a2da61eda7d0875156c728cbdc917aacdae964d5ce926ce1ce7789b15d4)
mongodb.setting.cluster.local.min-size=2
mongodb.setting.router-type=simple

helloworld.crypto.password=jenie
helloworld.crypto.salt=c73afbb57eb418d9