# server
spring.application.name=jenie-spring-helloworld-grpc-reactive
spring.grpc.server.port=30008

# mongodb
mongodb.setting.enabled=true
mongodb.setting.app-name=jenie-spring-helloworld-grpc-reactive

# logging
logging.config=classpath:logback-spring.xml