# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build
on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        project:
          - jenie-spring-core
          - jenie-spring-data-mongodb
          - jenie-spring-helloworld-common
          - jenie-spring-helloworld-web
          - jenie-spring-helloworld-rest
          - jenie-spring-helloworld-rest-reactive
          - jenie-spring-helloworld-grpc
          - jenie-spring-helloworld-grpc-reactive
          - jenie-spring-helloworld-armeria-grpc
          - jenie-spring-helloworld-armeria-grpc-reactive
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Check Format, Style
        run: ./gradlew :checkFormat :checkStyleMain :checkStyleTest
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build and publish ${{ matrix.project }}
        run: ./gradlew :${{ matrix.project }}:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
